### ISSUE TITLE
Git Changes Window Not Displaying

### ISSUE THREAD

**Issue by Dacke** [yysun/git-tools#38]
@yysun After the last update of Visual Studio 2019, I am no longer able to open the Git Changes window.  I can perform any other action on the extensions menu other than that one.  I really loved the visual representation and ease of use of your extension.  Do you have any idea that would help debug the problem?

Here is a copy of the message that finally arrived a long time after the window finally appeared and sat blank for about an hour.
<pre>
An exception was encountered while constructing the content of this frame.  This information is also logged in "C:\Users\EricDorothy\AppData\Roaming\Microsoft\VisualStudio\16.0_c0fc7721\ActivityLog.xml".

Exception details:
System.MissingMethodException: No parameterless constructor defined for this object.
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Microsoft.VisualStudio.Shell.Package.InstantiateToolWindow(Type toolWindowType, Object context)
   at Microsoft.VisualStudio.Shell.Package.InstantiateToolWindow(Type toolWindowType)
   at Microsoft.VisualStudio.Shell.Package.<>c__DisplayClass81_0.<CreateToolWindow>g__CreateToolWindowWorker|1()
   at Microsoft.VisualStudio.Shell.Package.CreateToolWindow(Type toolWindowType, Int32 id, UInt32 flags, Object context, Guid persistenceGuid)
   at Microsoft.VisualStudio.Shell.Package.CreateToolWindow(Type toolWindowType, Int32 id, Object context)
   at Microsoft.VisualStudio.Shell.Package.CreateToolWindow(Type toolWindowType, Int32 id)
   at Microsoft.VisualStudio.Shell.Package.<>c__DisplayClass91_1.<<FindToolWindow>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.<JoinAsync>d__68.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask`1.<JoinAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Shell.Package.<>c__DisplayClass91_0.<<FindToolWindow>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Shell.ToolWindowCollection.ToolWindowListener.<>c__DisplayClass1_0.<<-ctor>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.AwaitExtensions.ExecuteContinuationSynchronouslyAwaiter`1.GetResult()
   at Microsoft.VisualStudio.Threading.AsyncLazy`1.<>c__DisplayClass13_0.<<GetValueAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.AsyncLazy`1.GetValue(CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Shell.Package.CreateToolWindow(Type toolWindowType, Int32 id, UInt32 flags, Object context, Guid persistenceGuid)
   at Microsoft.VisualStudio.Shell.Package.CreateToolWindow(Type toolWindowType, Int32 id, Object context)
   at Microsoft.VisualStudio.Shell.AsyncPackage.Microsoft.VisualStudio.Shell.Interop.IVsAsyncToolWindowFactory.CreateToolWindow(Guid toolWindowType, UInt32 id, Object context)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.<CreateToolWindowAsync>d__145.MoveNext()
</pre>

**Comment by neon-dev** [comment]
Same here, @yysun

**Comment by AlbertWaelti** [comment]
I have the same problem. When selecting the menu "Extensions / Git Tools / Git Changes", no window is displayed.

**Comment by yysun** [comment]
I will take a look.  Meanwhile someone told me that uninstall and reinstall
twice might fix it.

**Comment by AlbertWaelti** [comment]
When starting first Visual Studio and then opening the solution, it seems to work. When stating Visual Studio by clicking on my solution I get the same exception as mentioned above by Dacke.
Hoping this may help to solve the problem... :=)

**Comment by unicrus** [comment]
Same here. Re-installing the addon (twice) didn't help.

**Comment by ampleecant** [comment]
Same here, I tried installing several times and re-starting. It's just the GitChanges window that doesn't work for me, everything else is fine.

**Comment by leerobertcant1** [comment]
Same here Unicrus. I've tried re-installing twice, re-starting you name it. It started happening about 2 updates ago from Visual Studio. Which is a shame, this is a really nice easy extension to use.

**Comment by leerobertcant1** [comment]
Okay Unicrus, after many  headaches and testing I've just got it working! here's what I did.

1. Launch Visual Studio, but when you launch it select: "continue without code".
2. Re-install and install, I did it around 3 times(do not click Git changes), at each stage make sure you do 1 when launching.
3. Restart your computer.
4. Launch Visual Studio, but when you launch it select: "continue without code".
5. Before opening a solution click the "Git changes" in your Visual Studio.

After this it should appear and  when you select any solution from the shortcut menu it should already be there.

**Comment by Dacke** [comment]
> Okay Unicrus, like you I had the same problems but after many headaches and testing I've just got it working! here's what I did.
> 
> 1. Launch Visual Studio, but when you launch it select: "continue without code".
> 2. Re-install and install, I did it around 3 times(do not click Git changes), at each stage make sure you do 1 when launching.
> 3. Restart your computer.
> 4. Launch Visual Studio, but when you launch it select: "continue without code".
> 5. Before opening a solution click the "Git changes" in your Visual Studio.
> 
> After this it should appear and when you select any solution from the shortcut menu it should already be there.

Thanks, got me going in the meantime. I'll be curious what the fix is so I don't have to use this work around anymore

**Comment by richardvaldiviesomacias** [comment]
Sadly I cannot open Git Changes windows at all. Is there any fix?

**Comment by cliesens27** [comment]
Just upgraded to VS 2019 from 2017 & installed Git Tools 2019, and I was hoping it would work fine since I've never had any issues with the 2017 version, but I've experiencing the same issue described here.

I tried @leerobertcant1's fix multiple times, which worked once or twice, but after an hour or so the Git Tools window keeps crashing or becoming unresponsive (or not even showing at all). Now it just won't show up anymore no matter how many times in reinstall it.

**Comment by NightOwl888** [comment]
Same here. This problem is happening for me in Visual Studio 2019. "Continue without code" seems to fix it every time, but this is really annoying when Visual Studio crashes and reloads the whole solution without going through this step, then I have to close and reopen Visual Studio again in order to get the Git Changes window back (that is 2 complete reloads of a large solution in a row, which is very time consuming).

**Comment by yysun** [comment]
I have fixed the 'No parameterless constructor' exception and publish V3.1.2.

Please give it a try.

**Comment by cliesens27** [comment]
It seems to be working properly for now, though I've only been using it for thirty minutes or so. Thanks!

**Comment by Dacke** [comment]
I tried it with the main solution that I work with and it appears to now be working correctly.
